"""
Django settings for gym project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url  # <-- added
# from gym import create_superuser



BASE_DIR = Path(__file__).resolve().parent.parent

# ================== CORE SECURITY SETTINGS ==================

# SECRET_KEY & DEBUG env se, taki production safe rahe
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-s^n%upt(cm*^h5t7rs^12!m(%z87y67b3egk#es$6@t%z=rzu_"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

# Render pe pehle * rakho, baad me exact domain bhi dal sakte ho
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# ================== APPLICATIONS ==================

INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party (optional)
    # 'whitenoise.runserver_nostatic',  # dev me chahiye to uncomment

    # Local apps
    'fitness',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Whitenoise for static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym.wsgi.application'

# ================== DATABASE ==================

# Render / production friendly: DATABASE_URL ho to use karega,
# warna default sqlite use karega
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fitness_place_db',
        'USER': 'fitness_user',
        'PASSWORD': 'StrongPassword123!',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# ================== AUTH & PASSWORD ==================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ================== I18N ==================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'  # chaho to 'Asia/Kolkata' bhi kar sakte ho
USE_I18N = True
USE_TZ = True

# ================== STATIC FILES ==================

STATIC_URL = '/static/'

# yaha Render collectstatic ka output daalega
STATIC_ROOT = BASE_DIR / 'staticfiles'

# tera local static folder
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Whitenoise ko compressed files serve karne do
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ================== LOGIN / LOGOUT ==================

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'membership'
LOGOUT_REDIRECT_URL = 'index'

# ================== DEFAULT PRIMARY KEY ==================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================== RAZORPAY KEYS ==================

RAZORPAY_KEY_ID = os.environ.get(
    "RAZORPAY_KEY_ID",
    "rzp_test_RoLXSJ1Ssf6w3k"   # local / test ke liye default
)

RAZORPAY_KEY_SECRET = os.environ.get(
    "RAZORPAY_KEY_SECRET",
    "KZPSZMwmnapvEOTbyWQ3CD4r"
)
