# Generated by Django 5.2.7 on 2025-12-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_lead_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
    ]
